version: 0.0
os: linux
files:
  - source: /
    destination: /home/artsy/fe
    overwrite: yes

permissions:
  - object: /home/artsy
    pattern: '**'
    owner: www-data
    group: www-data

hooks:
  BeforeInstall:
    - location: scripts/move_previous.sh
      timeout: 300
      runas: root
