const ERROR_TYPE = {
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    NOT_FOUND_EMAIL: 'NOT_FOUND_EMAIL',
    INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    INVALID_PARAM: 'INVALID_PARAM',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

export { ERROR_TYPE };
